# Generated by Django 5.0.1 on 2024-01-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategories',
            field=models.ManyToManyField(to='store.subcategory'),
        ),
    ]
